<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
<name>Turkarta Vemdalen</name>
<layers>
<layer>
<retina>1</retina>
<url>http://static.hitta.se/tile/v3/0_2x/{$z}/{$x}/{$invY}</url>
</layer>
<layer>
<minZoom>9</minZoom>
<maxZoom>14</maxZoom>
<retina>2</retina>
<url>https://johanberonius.github.io/Lantmateriets-Fjallkarta/Turkarta-Vemdalen/{$z}/{$x}/{$y}.png</url>
</layer>
</layers>
</customMapSource>
